name: Vercel Beta Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID_PRD }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_PRD }}
on:
   pull_request:
     branches:
       - beta
     types:
       [closed]
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN_PRD }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN_PRD }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN_PRD }}